[env]
TERM = "xterm-256color"
COLOR_SCHEME = "light"

[font]
size = 19.5

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Regular"

[window]
decorations = "buttonless"
opacity = 0.95

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 5
y = 5

# Default colors
[colors.primary]
background = '#f9f5d7' # base
foreground = '#1d2021' # text

# Cursor colors
[colors.cursor]
text = '#f9f5d7' # base
cursor = '#ea6962' # rosewater

[colors.vi_mode_cursor]
text = '#f9f5d7' # base
cursor = '#45707a' # lavender

# Search colors
[colors.search.matches]
foreground = '#f9f5d7' # base
background = '#805942' # subtext0

[colors.search.focused_match]
foreground = '#f9f5d7' # base
background = '#6c782e' # green

[colors.footer_bar]
foreground = '#f9f5d7' # base
background = '#805942' # subtext0

# Keyboard regex hints
[colors.hints.start]
foreground = '#f9f5d7' # base
background = '#b47109' # yellow

[colors.hints.end]
foreground = '#f9f5d7' # base
background = '#805942' # subtext0

# Selection colors
[colors.selection]
text = '#f9f5d7' # base
background = '#ea6962' # rosewater

# Normal colors
[colors.normal]
black = '#73503c' # subtext1
red = '#c14a4a' # red
green = '#6c782e' # green
yellow = '#b47109' # yellow
blue = '#45707a' # blue
magenta = '#945e80' # pink
cyan = '#4c7a5d' # teal
white = '#bfb695' # surface2

# Bright colors
[colors.bright]
black = '#805942' # subtext0
red = '#c14a4a' # red
green = '#6c782e' # green
yellow = '#b47109' # yellow
blue = '#45707a' # blue
magenta = '#945e80' # pink
cyan = '#4c7a5d' # teal
white = '#d1c7a3' # surface1

# Dim colors
[colors.dim]
black = '#73503c' # subtext1
red = '#c14a4a' # red
green = '#6c782e' # green
yellow = '#b47109' # yellow
blue = '#45707a' # blue
magenta = '#945e80' # pink
cyan = '#4c7a5d' # teal
white = '#bfb695' # surface2
