[env]
TERM = "xterm-256color"

[font]
size = 19.5

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Regular"

[window]
decorations = "buttonless"
opacity = 0.95

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 5
y = 5

[cursor]
style = "Block"
unfocused_hollow = true

[[colors.indexed_colors]]
color = "#FAB387"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

[colors.bright]
black = "#4B4F51"
blue = "#89B4FA"
cyan = "#7DAEA3"
green = "#A9B665"
magenta = "#D3869B"
red = "#EA6962"
white = "#A69372"
yellow = "#D8A657"

[colors.cursor]
cursor = "#fcb103"
text = "#333333"

[colors.dim]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[colors.normal]
black = "#4B4F51"
blue = "#89B4FA"
cyan = "#7DAEA3"
green = "#A9B665"
magenta = "#D3869B"
red = "#EA6962"
white = "#BDAE8B"
yellow = "#D8A657"

[colors.primary]
background = "#1D2021"
bright_foreground = "#D4BE98"
dim_foreground = "#D4BE98"
foreground = "#D4BE98"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[colors.vi_mode_cursor]
cursor = "#fcb103"
text = "#333333"
