return {
  -- "shellRaining/hlchunk.nvim",
  -- event = { "BufReadPre", "BufNewFile" },
  -- config = function()
  --   require("hlchunk").setup({
  --     chunk = {
  --       enable = true,
  --       chars = {
  --         horizontal_line = "─",
  --         vertical_line = "│",
  --         left_top = "╭",
  --         left_bottom = "╰",
  --         right_arrow = ">",
  --       },
  --       style = "#806d9c",
  --     },
  --     indent = {
  --       enable = true,
  --     },
  --   })
  -- end,
}
